### ISSUE TITLE
add features with descriptions

### ISSUE THREAD

**Issue by Tarkan-Zarrouk** [TheDucky/Html-Basics#1]
video 
 link to embed a video, simply using code from youtube or any external platform.

em 
 emphasis

br 
 Line break element

Strong 
 Bold

anchor 
 anchor used for hyperlinks refering to other websites by surrounding a paragraph or any html class

tr 
 Table row element add rows to a table

td 
 Table data adding a new cell/block to the table element

thead 
 defines headings for table collumn
some other table stuff I forgot about

input type radio 
 uses radio buttons aka the circle thingies

form 
    creates form element, u can use https://formsubmit.co/ it's very nice

placeholder for input 
                             creates a placeholder that can be used to distinguish different inputs making it more clear ( like a login system)

password input type |
hides chars 👍 

section  
can be used to space tags this can be done with article too

list 
 pretty straight forward, creates a list

figure 
 use to cover media tags

Of course, there are thousands of other HTML tags but these are pretty important too, ofc but I do not remember any of them lol. I also don't have time to make a pr, if I could I would but I cant 😢 .

**Comment by TheDucky** [comment]
thank you for the issue post. I am aware that many tags are missing. I've been very busy lately and don't have time for any contributions. I have also forgotten this repo exists 😅. I will definitely try to do the needful...
